import type { Metadata } from 'next';
import clsx from 'clsx';
import { gothamFont } from '@/config/font';
import './globals.css';
import Providers from './provider';

export const metadata: Metadata = {
    title: 'Popcorn Time',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={clsx(gothamFont.className, 'antialiased')}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
